### ISSUE TITLE
[ENH]: Support K8s API 1.28.0

### ISSUE THREAD

**Issue by d3287t328** [amikos-tech/chromadb-chart#14] opened 2023-08-26 20:32 UTC
### What happened?

Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.23.0 <= 1.27.x which is incompatible with Kubernetes v1.28.0

### ChromaDB Version

0.4.3

### Kubernetes Version

1.27.x

### Environment details

kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0

**Comment by tazarov** [comment] 2023-08-27 04:50
Hey @d3287t328, thanks for raising this. Frankly speaking, this is not a bug but rather a feature request. I will try adding 1.28 to the test matrix, as nothing prevents the chart from deploying to 1.28. WIll try to get this done today.

**Comment by tazarov** [comment] 2023-08-27 06:09
@d3287t328 Things seem to be working. I'll release it at little later today - https://github.com/amikos-tech/chromadb-chart/actions/runs/5989120529

**Comment by tazarov** [comment] 2023-08-27 11:51
@d3287t328 this should be now fixed give it a try with latest chart version (don't forget to `helm repo update`  first) and let me know.

**Closed** 2023-08-27 12:50 UTC
Labels: enhancement

**Comment by tazarov** [comment] 2023-08-27 13:45
No problem. Let me know if you need more Chart features. I am working on best efforts basis for backup/restore and security features but if there is an actual need for it I can prioritize.
